### ISSUE TITLE
changing password from mobile phone causes server error

### ISSUE THREAD

**Issue by papeg** [filehoarder/ep_password_change#10]
Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
    at ServerResponse.removeHeader (_http_outgoing.js:586:11)
    at ServerResponse.send (/home/papeg/ep/etherpad-lite/src/node_modules/express/lib/response.js:210:10)
    at ServerResponse.res.send (/home/papeg/ep/etherpad-lite/src/node/hooks/express/webaccess.js:105:14)
    at /home/papeg/ep/etherpad-lite/ep_password_change/index.js:63:49
    at /home/papeg/ep/etherpad-lite/src/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:136:16
    at /home/papeg/ep/etherpad-lite/src/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:57:14
    at FSReqCallback.oncomplete (fs.js:155:23)

this may mean that the response object is called twice?!

**Comment by papeg** [comment]
might be solved by doing everything synchronously
